project:
  type: website
  output-dir: docs

website:
  title: "Gestion de base de données bibliographiques"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - formations.qmd

format:
  html:
    theme: simplex
    mainfont: arial
    fontsize: 1rem
    css: styles.css
    toc: true



